/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itpm.assi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vinuka Wathsara
 */
public class Des6 extends javax.swing.JFrame {

    /**
     * Creates new form Des6
     */
    public Des6() {
        initComponents();
        DisplayTable();
    }
    
    private void DisplayTable()
    {
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/itpm project?zeroDateTimeBehavior=convertToNull","root","");
         
         String sql = "select * from addlocation";
         
         PreparedStatement pstmt = conn.prepareStatement(sql);
         ResultSet rs = pstmt.executeQuery();
         
         retrieveLoc.setModel(DbUtils.resultSetToTableModel(rs));
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
  /**  
    retrieveLoc.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example// print first column value from selected row
            System.out.println(retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 0).toString());
        }
    });
**/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        retrieveLoc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bldName1 = new javax.swing.JTextField();
        rmName1 = new javax.swing.JTextField();
        lecHall1 = new javax.swing.JRadioButton();
        lab1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cpcty1 = new javax.swing.JTextField();
        updateLoc = new javax.swing.JButton();
        deleteLoc = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sText = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Locations");

        jButton1.setBackground(new java.awt.Color(46, 58, 96));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(339, 339, 339)
                .addComponent(jLabel6)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        retrieveLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Building", "Room", "Room Type", "Capacity"
            }
        ));
        retrieveLoc.setFocusable(false);
        retrieveLoc.setRowHeight(25);
        retrieveLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrieveLocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(retrieveLoc);

        jLabel2.setText("Building Name");

        jLabel3.setText("Room Name");

        jLabel4.setText("Room Type");

        bldName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bldName1ActionPerformed(evt);
            }
        });

        rmName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmName1ActionPerformed(evt);
            }
        });

        lecHall1.setText("Lecture Hall");

        lab1.setText("Laboratory");

        jLabel5.setText("Capacity");

        updateLoc.setBackground(new java.awt.Color(106, 116, 145));
        updateLoc.setForeground(new java.awt.Color(255, 255, 255));
        updateLoc.setText("Update");
        updateLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLocActionPerformed(evt);
            }
        });

        deleteLoc.setBackground(new java.awt.Color(106, 116, 145));
        deleteLoc.setForeground(new java.awt.Color(255, 255, 255));
        deleteLoc.setText("Delete");
        deleteLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(106, 116, 145));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Search for the Room ID for Update/Delete(Optional)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bldName1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(rmName1))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(37, 37, 37)
                                        .addComponent(lecHall1)
                                        .addGap(40, 40, 40)
                                        .addComponent(lab1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(45, 45, 45)
                                        .addComponent(cpcty1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(sText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(deleteLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cpcty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bldName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lecHall1)
                            .addComponent(lab1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rmName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        ClearFields();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    
    //UPDATE 
    private void updateLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLocActionPerformed
        // TODO add your handling code here:
         try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/itpm project?zeroDateTimeBehavior=convertToNull","root","");
         
         String sql = "update addlocation set roomName = ?, buildingName = ?, roomType = ?, capacity = ? where roomID = ?";
         
         PreparedStatement pstmt = conn.prepareStatement(sql);
         
         pstmt.setString(2,bldName1.getText());
            pstmt.setString(1, rmName1.getText());
            
            String roomTp = null;
            if(lecHall1.isSelected())
            {
                        roomTp = lecHall1.getText();
            };
            
            if(lab1.isSelected())
            {
                        roomTp = lab1.getText();
            };
            
            pstmt.setString(3,roomTp);
            
            pstmt.setString(4, cpcty1.getText());
            
            pstmt.setInt(5, Integer.parseInt(sText.getText()));
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully!!!");
         
         conn.close();
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
         
        DisplayTable(); 
    }//GEN-LAST:event_updateLocActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        
        
        
        
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/itpm project?zeroDateTimeBehavior=convertToNull","root","");
         
         String sql = "select * from addlocation where roomID = ? ";
         PreparedStatement pstmt = conn.prepareStatement(sql);
         pstmt.setInt(1,Integer.parseInt(sText.getText()));
         
         ResultSet rs = pstmt.executeQuery();
         if(rs.next())
         {
             bldName1.setText(rs.getString("buildingName"));
             rmName1.setText(rs.getString("roomName"));
             cpcty1.setText(rs.getString("capacity"));
             
             String roomTp = rs.getString("roomType");
             if(roomTp.equalsIgnoreCase("Laboratory"))
            {
                         lecHall1.setSelected(false);
                         lab1.setSelected(true);
            };
            
            if(roomTp.equalsIgnoreCase("Lecture Hall"))
            {
                         lab1.setSelected(false);
                         lecHall1.setSelected(true);
            };
             
         }
         else{
             ClearFields();
         JOptionPane.showMessageDialog(null,"No Such Field !!!");
         }
         
          }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocActionPerformed
        // TODO add your handling code here:
        
        try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/itpm project?zeroDateTimeBehavior=convertToNull","root","");
         
         String sql = "delete from addlocation where roomID = ? ";
         PreparedStatement pstmt = conn.prepareStatement(sql);
         pstmt.setInt(1,Integer.parseInt(sText.getText()));
         
         int result = pstmt.executeUpdate();
         if( result > 0 ){
         
           JOptionPane.showMessageDialog(null, "Record Deleted Successfully!!!");
           ClearFields();
         }
         else{
         JOptionPane.showMessageDialog(null, "Record Could Not Be Found");
         }
        
          
          }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
        
       DisplayTable(); 
    }//GEN-LAST:event_deleteLocActionPerformed

    private void retrieveLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrieveLocMouseClicked
        // TODO add your handling code here
        
        sText.setText( retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 0).toString());
        bldName1.setText( retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 1).toString());
             rmName1.setText( retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 2).toString());
             cpcty1.setText( retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 4).toString());
             
             String roomTp =  retrieveLoc.getValueAt(retrieveLoc.getSelectedRow(), 3).toString();
             if(roomTp.equalsIgnoreCase("Laboratory"))
            {
                         lecHall1.setSelected(false);
                         lab1.setSelected(true);
            };
            
            if(roomTp.equalsIgnoreCase("Lecture Hall"))
            {
                         lab1.setSelected(false);
                         lecHall1.setSelected(true);
            };
    }//GEN-LAST:event_retrieveLocMouseClicked

    private void bldName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bldName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bldName1ActionPerformed

    private void rmName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmName1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new homePg().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Des6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Des6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Des6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Des6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Des6().setVisible(true);
            }
        });
    }
    private void ClearFields(){
        sText.setText("");
        bldName1.setText( "");
        rmName1.setText( "");
        cpcty1.setText( "");
             
        lecHall1.setSelected(false);
        lab1.setSelected(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bldName1;
    private javax.swing.JTextField cpcty1;
    private javax.swing.JButton deleteLoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lab1;
    private javax.swing.JRadioButton lecHall1;
    private javax.swing.JTable retrieveLoc;
    private javax.swing.JTextField rmName1;
    private javax.swing.JTextField sText;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateLoc;
    // End of variables declaration//GEN-END:variables
}
